# fly.toml app configuration file generated for y-elpcamp on 2023-08-10T11:36:52+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "y-elpcamp"
primary_region = "jnb"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
